version: '3.3'

services:
 db:
  image: mysql:5.7
  hostname: mysql
  ports:
   - "3306:3306"
  volumes:
   - db_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: mysqldb1

volumes:
  db_data: {}

